### ISSUE TITLE
rake db:setup - Unable to autoload constant PendingVolunteer...

### ISSUE THREAD

**Issue by mfrederickson** [tescher/rol#6]
Here's the partial output...  any ideas?
```
-- initialize_schema_migrations_table()
   -> 0.0205s
rake aborted!
LoadError: Unable to autoload constant PendingVolunteer, expected /mnt/683fd734-8323-4ac0-a2ba-1436ff10f137/data2/projects/rol/app/models/pending_volunteer.rb to define it
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/core_ext/string/inflections.rb:77:in `safe_constantize'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:475:in `block in []'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:474:in `fetch'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:474:in `[]'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:512:in `block (2 levels) in create_fixtures'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:511:in `map'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:511:in `block in create_fixtures'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:17:in `disable_referential_integrity'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:508:in `create_fixtures'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/deprecation/proxy_wrappers.rb:24:in `method_missing'
/mnt/683fd734-8323-4ac0-a2ba-1436ff10f137/data2/projects/rol/db/seeds.rb:15:in `block in <top (required)>'
/mnt/683fd734-8323-4ac0-a2ba-1436ff10f137/data2/projects/rol/db/seeds.rb:13:in `each'
/mnt/683fd734-8323-4ac0-a2ba-1436ff10f137/data2/projects/rol/db/seeds.rb:13:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.10/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/engine.rb:547:in `load_seed'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/usr/local/rvm/gems/ruby-2.1.10/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.10/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

**Comment by tescher** [comment]
OK, what is happening is that the PendingVolunteer table is no longer used
so the model was commented out. If you look at
models/pending_volunteer.rb you'll see it. But there are still migrations
that try to run to get the tables up to date.

I would try uncommenting that file and see if that fixes it. It is
something we should fix.

Tim Escher
tim@eschers.com
608-432-5799

**Comment by mfrederickson** [comment]
I was able to delete the seed fixture for pending volunteers, and then I was able to run the db:seed successfully.  Thanks.

**Comment by tescher** [comment]
Closing. Uncommented headers so migrations work
