### ISSUE TITLE
check address for new volunteer isn't working

### ISSUE THREAD

**Issue by mfrederickson** [tescher/rol#8]
In development, console shows the following
```


Started GET "/resschecks/search?dialog=true&_=1505246257747" for 127.0.0.1 at 2017-09-12 11:57:53 -0800

ActionController::RoutingError (No route matches [GET] "/resschecks/search"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/routing_error.text.erb (4.1ms)


Started GET "/volunteers/address_check?_=1505246257748" for 127.0.0.1 at 2017-09-12 11:57:53 -0800
Processing by VolunteersController#show as */*
  Parameters: {"_"=>"1505246257748", "id"=>"address_check"}
  Volunteer Load (0.6ms)  SELECT  "volunteers".* FROM "volunteers" WHERE "volunteers"."deleted_at" IS NULL AND "volunteers"."needs_review" = 'f' AND "volunteers"."id" = $1 LIMIT 1  [["id", 0]]
Completed 404 Not Found in 3ms

ActiveRecord::RecordNotFound (Couldn't find Volunteer with 'id'=address_check [WHERE "volunteers"."deleted_at" IS NULL AND "volunteers"."needs_review" = 'f']):
  app/controllers/volunteers_controller.rb:216:in `show'


  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (1.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.1.10/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (15.4ms)
```

**Comment by mfrederickson** [comment]
It appears you may need to save the volunteer before you check the address, but that's not clearly stated.  Once I saved the volunteer and then checked the address I got the following failure message in the console, and a window that lets me cancel, but doesn't tell me anything about the validity of the address.

Started GET "/volunteers/980190963/address_check.json?address=%7B%22street%22%3A%22123+Any+St%22%2C%22city%22%3A%22Soldotna%22%2C%22state%22%3A%22AK%22%2C%22postal_code%22%3A%2299669%22%7D" for 127.0.0.1 at 2017-09-12 12:07:22 -0800
Processing by VolunteersController#address_check as JSON
  Parameters: {"address"=>"{\"street\":\"123 Any St\",\"city\":\"Soldotna\",\"state\":\"AK\",\"postal_code\":\"99669\"}", "id"=>"980190963"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 762146111]]
Completed 500 Internal Server Error in 2ms

```
Fedex::RateError (Missing Required Parameter key):
  app/controllers/volunteers_controller.rb:31:in `new'
  app/controllers/volunteers_controller.rb:31:in `block (2 levels) in address_check'
  app/controllers/volunteers_controller.rb:20:in `address_check'
```

Appears to be hanging, though I can click Cancel.
![image](https://user-images.githubusercontent.com/473165/30345910-79b94a8a-97b3-11e7-9ef4-5ca09f8c431c.png)
